### ISSUE TITLE
Forward slash conversion bug

### ISSUE THREAD

**Issue by Kpoi** [hankhero/cl-json#10]
The ENCODE-JSON type functions convert forward slashes into a backward and forward slash combo.
For example:
CL-USER> (json:encode-json '(("example" . "/")))
{"example":"\/"}
that is not a letter "v" it is a backward slash "\" then a forward slash. The previous should output
{"example":"/"}
note the difference.
it also works with ENCODE-JSON-TO-STRING
CL-USER> (json:encode-json-to-string '(("example" . "/")))
"{\"example\":\"\\/\"}"
I am going to try to find the culprit in the source. Should I find it I will submit a pull request with the fixed version. Does anyone here have a workaround I could use?

**Comment by hankhero** [comment]
Hello, actually this may seem surprising but it is not a bug, it is a valid JSON representation of /.
If you look at the syntax spec on json.org you can see this. It might not be a strictly necessary encoding, but since \ and " are forced to be treated similarly and / is there with them, that was probably why it was done like this. For machine-reading purposes it is all valid so should not be a problem.

Showing the out of a decode in javascript/jquery
    > $.parseJSON('{"example":"\/"}')
    Object {example: "/"}
