### ISSUE TITLE
Broken Key and keywords encode/decode

### ISSUE THREAD

**Issue by diegogub** [hankhero/cl-json#32]
Hello, 
All my key are changing after encode/decode. They look like:  "5d8c7d436887d|c585b183|4a3ff62b|IT" 
The first part is being uncased and changed completely .

How can I solve it or help you solve it?

Thanks

**Comment by rpgoldman** [comment]
Please post an example that we can run and that illustrates the problem.  I can't understand your problem given only what you have posted.

**Comment by diegogub** [comment]
Sure, I have an API that gives this output;

`(cl-json:decode-json-from-string "{ \"5eb4c75f52c1b|afd31959|f0b48cf1|HK\":{\"clicks\":1}}")
((:|5-EB-4-C-75-F-52-C-1-B\|AFD-31959\|F-0-B-48-CF-1\|+HK+| (:CLICKS . 1)))

(cl-json:encode-json-to-string *)
"{\"5Eb4C75F52C1B|afd31959|f0B48Cf1|+hk+\":{\"clicks\":1}}"
`
The resulting key is totally different from the one provided, technically it's a valid JSON key.

Thanks

**Comment by rpgoldman** [comment]
That is because your key is being decoded into a lisp symbol, instead of being read as a string.  This:

```
:|5-EB-4-C-75-F-52-C-1-B|AFD-31959|F-0-B-48-CF-1|+HK+| 
```

is a _very_ wonky symbol. If you are going to use keys like that you should get CL-JSON to keep them as strings, and not turn them into symbols.

This is a solution, but it's kind of yucky:

```
(let ((cl-json:*object-key-handler* 
                             #'(lambda (x) 
                                 (let ((json:*identifier-name-to-key* #'identity))
                                   (json::accumulator-add-key x)))))
                       (cl-json:decode-json-from-string "{ \"5eb4c75f52c1b|afd31959|f0b48cf1|HK\":{\"clicks\": 1}}"))
```

If this solves your problem, please reply and close this ticket.

**Comment by rpgoldman** [comment]
Better yet, make a PR to add this as a FAQ to the docs!

**Comment by diegogub** [comment]
Hello @rpgoldman , thank you for you help. Trying that code the output is different, as the key is a string , not keyword. but the value still changed.

(("5-EB-4-C-75-F-52-C-1-B|AFD-31959|F-0-B-48-CF-1|+HK+" ("CLICKS" . 1)))
--
((:|5-EB-4-C-75-F-52-C-1-B\|AFD-31959\|F-0-B-48-CF-1\|+HK+| (:CLICKS . 1)))

Not sure if that's the intended behaviour.
Thanks

**Comment by rpgoldman** [comment]
```
> (let ((cl-json:*object-key-handler* 
                             #'(lambda (x) 
                                 (let ((json:*identifier-name-to-key* #'identity))
                                   (json::accumulator-add-key x)))))
                       (cl-json:decode-json-from-string "{ \"5eb4c75f52c1bafd31959f0b48cf1HK\":{\"clicks\": 1}}"))
(("5-EB-4-C-75-F-52-C-1-BAFD-31959-F-0-B-48-CF-1-+HK+" ("CLICKS" . 1)))
```

This is happening (the hyphenation) because CL-JSON is trying to translate this into a "lispy" name by adding the hyphens.  This is also controllable.  

These structures you are reading are special enough that you probably need to write a tailored reader for them. They don't fit what the stock encoder and decoder expect, and you would need to treat these keys specially (you don't want to mess up processing of keys inside these structures).

**Comment by diegogub** [comment]
I see, thank you for your help.
 Thinking it better, what if can change the output of this API to emit lisp structure? 
May be silly question,  I'm quite new to common lisp.
